### ISSUE TITLE
Alien !crit x

### ISSUE THREAD

**Issue by PseudoWyvern** [Stefouch/sebedius-yearzero-discord-bot#125]
### Describe the Bug

When using !crit x for AlienRPG, two dice are rolled instead of one, the most common results are Rise Again and Torn Apart (1 and 6 on the table respectively), with the only other result being Wounded.

### Severity

- High (a broken feature, major functional impact)

### Context

!crit x !crit xeno 

### To Reproduce

It seems that it happens no matter what - no step process required just type !crit x with the bot active

### Expected behavior

should be a single D6 roll, not 2, with an equal chance of rolling one of the 6 options on the Critical table for a Xenomorph

**Comment by mprangenberg** [comment]
The xenomorph has only 5 options on it's crit table (1, 2, 3, 4 and 5-6). Because of internal develoment reasons all crit rolls are performed as a d66 roll. The options have been mapped to 1 = 11-16, 2 = 21-26, 3 = 31-36, 4 = 41-46 and 5-6 = 51-66, so the last option "Torn Apart" should statistically happen more often (as dictated by the original crit table).
I just tested it a few times and see no bug in the rolling of the dice with any preference.
