### ISSUE TITLE
Vaesen Dice faces blank or 6, no others (minor)

### ISSUE THREAD

**Issue by aramis-erak** [Stefouch/sebedius-yearzero-discord-bot#35]
the images for the vaesen dice do not show the numbers on non-6 faces. My players tend to shade narrative failure based upon the height on the various failure results. This is minor because the summary box does show the numbers.
![image](https://user-images.githubusercontent.com/43119398/91366511-c72f8380-e7b8-11ea-98b1-cec84b7dbeb6.png)

**Comment by Stefouch** [comment]
Yes, this is a limitation due to Discord. The bot uses custom emojis to illustrate the dice faces. Unfortunately, there is a limited number of slots available in a single Discord server (50).

I am currently using **89** slots over two private servers:
- Forbidden Lands: **30**
- Mutant Year Zero: **24**
- Twilight 2000: **17**
- Alien RPG: **12**
- Tales From the Loop: **2**
- Coriolis: **2**
- Vaesen: **2**

Since the supported games here don't have any mechanical use for the numbered faces (not six or bane), I chose to skip them to spare some free slots (and free time to design them).
Alien RPG still uses 2×6 slots because it also serves as a default layout for other rolls.
Forbidden Lands & Mutant Year Zero display a full set of dice emojis because they date from early stages of the bot when it was not really planned to support more games. So I was greedy on slots at that time.
Twilight 2000 uses a lot of slots, but they are actually the minimum unnumbered.

One solution could just to create a third Discord server and upload the extra dice emojis on it. But there were not much demand from the community before for this so I never took the hassle to design more dice faces for Tales From the Loop, Coriolis and Vaesen.

If there is more demand for this, then I'll probably have to change my mind and start considering it. But It's just at the moment my free time is taken on other features for the bot.

**Comment by aramis-erak** [comment]
Thanks for the explanation.

Sent from Mail for Windows 10
